// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostFinishOKCode is the HTTP code returned for type PostFinishOK
const PostFinishOKCode int = 200

/*PostFinishOK The level has been accepted.

swagger:response postFinishOK
*/
type PostFinishOK struct {

	/*
	  In: Body
	*/
	Payload *PostFinishOKBody `json:"body,omitempty"`
}

// NewPostFinishOK creates PostFinishOK with default headers values
func NewPostFinishOK() *PostFinishOK {

	return &PostFinishOK{}
}

// WithPayload adds the payload to the post finish o k response
func (o *PostFinishOK) WithPayload(payload *PostFinishOKBody) *PostFinishOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post finish o k response
func (o *PostFinishOK) SetPayload(payload *PostFinishOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFinishOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
