// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostRegOKCode is the HTTP code returned for type PostRegOK
const PostRegOKCode int = 200

/*PostRegOK An existing user.

swagger:response postRegOK
*/
type PostRegOK struct {

	/*
	  In: Body
	*/
	Payload *PostRegOKBody `json:"body,omitempty"`
}

// NewPostRegOK creates PostRegOK with default headers values
func NewPostRegOK() *PostRegOK {

	return &PostRegOK{}
}

// WithPayload adds the payload to the post reg o k response
func (o *PostRegOK) WithPayload(payload *PostRegOKBody) *PostRegOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reg o k response
func (o *PostRegOK) SetPayload(payload *PostRegOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRegCreatedCode is the HTTP code returned for type PostRegCreated
const PostRegCreatedCode int = 201

/*PostRegCreated A new user.  FE should instruct the user to check email.

swagger:response postRegCreated
*/
type PostRegCreated struct {

	/*
	  In: Body
	*/
	Payload *PostRegCreatedBody `json:"body,omitempty"`
}

// NewPostRegCreated creates PostRegCreated with default headers values
func NewPostRegCreated() *PostRegCreated {

	return &PostRegCreated{}
}

// WithPayload adds the payload to the post reg created response
func (o *PostRegCreated) WithPayload(payload *PostRegCreatedBody) *PostRegCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reg created response
func (o *PostRegCreated) SetPayload(payload *PostRegCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRegUnauthorizedCode is the HTTP code returned for type PostRegUnauthorized
const PostRegUnauthorizedCode int = 401

/*PostRegUnauthorized The given token is invalid.

swagger:response postRegUnauthorized
*/
type PostRegUnauthorized struct {
}

// NewPostRegUnauthorized creates PostRegUnauthorized with default headers values
func NewPostRegUnauthorized() *PostRegUnauthorized {

	return &PostRegUnauthorized{}
}

// WriteResponse to the client
func (o *PostRegUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostRegServiceUnavailableCode is the HTTP code returned for type PostRegServiceUnavailable
const PostRegServiceUnavailableCode int = 503

/*PostRegServiceUnavailable Firebase DB error.

swagger:response postRegServiceUnavailable
*/
type PostRegServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *PostRegServiceUnavailableBody `json:"body,omitempty"`
}

// NewPostRegServiceUnavailable creates PostRegServiceUnavailable with default headers values
func NewPostRegServiceUnavailable() *PostRegServiceUnavailable {

	return &PostRegServiceUnavailable{}
}

// WithPayload adds the payload to the post reg service unavailable response
func (o *PostRegServiceUnavailable) WithPayload(payload *PostRegServiceUnavailableBody) *PostRegServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reg service unavailable response
func (o *PostRegServiceUnavailable) SetPayload(payload *PostRegServiceUnavailableBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRegGatewayTimeoutCode is the HTTP code returned for type PostRegGatewayTimeout
const PostRegGatewayTimeoutCode int = 504

/*PostRegGatewayTimeout Blockchain RPC call failed.

swagger:response postRegGatewayTimeout
*/
type PostRegGatewayTimeout struct {

	/*
	  In: Body
	*/
	Payload *PostRegGatewayTimeoutBody `json:"body,omitempty"`
}

// NewPostRegGatewayTimeout creates PostRegGatewayTimeout with default headers values
func NewPostRegGatewayTimeout() *PostRegGatewayTimeout {

	return &PostRegGatewayTimeout{}
}

// WithPayload adds the payload to the post reg gateway timeout response
func (o *PostRegGatewayTimeout) WithPayload(payload *PostRegGatewayTimeoutBody) *PostRegGatewayTimeout {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reg gateway timeout response
func (o *PostRegGatewayTimeout) SetPayload(payload *PostRegGatewayTimeoutBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegGatewayTimeout) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(504)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
