// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostRegOKCode is the HTTP code returned for type PostRegOK
const PostRegOKCode int = 200

/*PostRegOK An existing user.

swagger:response postRegOK
*/
type PostRegOK struct {

	/*
	  In: Body
	*/
	Payload *PostRegOKBody `json:"body,omitempty"`
}

// NewPostRegOK creates PostRegOK with default headers values
func NewPostRegOK() *PostRegOK {

	return &PostRegOK{}
}

// WithPayload adds the payload to the post reg o k response
func (o *PostRegOK) WithPayload(payload *PostRegOKBody) *PostRegOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reg o k response
func (o *PostRegOK) SetPayload(payload *PostRegOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRegCreatedCode is the HTTP code returned for type PostRegCreated
const PostRegCreatedCode int = 201

/*PostRegCreated A new user.  FE should instruct the user to check email.

swagger:response postRegCreated
*/
type PostRegCreated struct {
	/*CORS origin bypass. TODO ek – remove this.

	 */
	AccessControlAllowOrigin string `json:"Access-Control-Allow-Origin"`

	/*
	  In: Body
	*/
	Payload *PostRegCreatedBody `json:"body,omitempty"`
}

// NewPostRegCreated creates PostRegCreated with default headers values
func NewPostRegCreated() *PostRegCreated {

	return &PostRegCreated{}
}

// WithAccessControlAllowOrigin adds the accessControlAllowOrigin to the post reg created response
func (o *PostRegCreated) WithAccessControlAllowOrigin(accessControlAllowOrigin string) *PostRegCreated {
	o.AccessControlAllowOrigin = accessControlAllowOrigin
	return o
}

// SetAccessControlAllowOrigin sets the accessControlAllowOrigin to the post reg created response
func (o *PostRegCreated) SetAccessControlAllowOrigin(accessControlAllowOrigin string) {
	o.AccessControlAllowOrigin = accessControlAllowOrigin
}

// WithPayload adds the payload to the post reg created response
func (o *PostRegCreated) WithPayload(payload *PostRegCreatedBody) *PostRegCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reg created response
func (o *PostRegCreated) SetPayload(payload *PostRegCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Access-Control-Allow-Origin

	accessControlAllowOrigin := o.AccessControlAllowOrigin
	if accessControlAllowOrigin != "" {
		rw.Header().Set("Access-Control-Allow-Origin", accessControlAllowOrigin)
	}

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRegUnauthorizedCode is the HTTP code returned for type PostRegUnauthorized
const PostRegUnauthorizedCode int = 401

/*PostRegUnauthorized The given token is invalid.

swagger:response postRegUnauthorized
*/
type PostRegUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *PostRegUnauthorizedBody `json:"body,omitempty"`
}

// NewPostRegUnauthorized creates PostRegUnauthorized with default headers values
func NewPostRegUnauthorized() *PostRegUnauthorized {

	return &PostRegUnauthorized{}
}

// WithPayload adds the payload to the post reg unauthorized response
func (o *PostRegUnauthorized) WithPayload(payload *PostRegUnauthorizedBody) *PostRegUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reg unauthorized response
func (o *PostRegUnauthorized) SetPayload(payload *PostRegUnauthorizedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
