// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PostRegResponse post reg response
// swagger:model postRegResponse
type PostRegResponse struct {

	// The player's Harmony account address.
	Account string `json:"account,omitempty"`

	// The player's Harmony account balance (in wei), represented
	// as a decimal integer.
	//
	Balance string `json:"balance,omitempty"`

	// The player's Harmony account address.
	Txid string `json:"txid,omitempty"`

	// Contentos user ID.
	UID string `json:"uid,omitempty"`
}

// Validate validates this post reg response
func (m *PostRegResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostRegResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostRegResponse) UnmarshalBinary(b []byte) error {
	var res PostRegResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
