// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi harmony-puzzle

    Schemes:
      https
    Host: puzzle-api.harmony.one
    BasePath: /v1
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
