// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Harmony Puzzle
Harmony Puzzle is a simple yet addictive blockchain-based puzzle game.



    Schemes:
      https
    Host: harmony-puzzle-ek.appspot.com
    BasePath: /v1
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
